name: wechat_assets_picker
description: An assets' picker written in pure Dart which looks like the one in WeChat, support multi asset pick from the device.
version: 4.2.2
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  extended_image:
    git:
      https://github.com/octaface/extended_image
  photo_manager: ">=0.5.8 <2.0.0"
  provider: ^4.3.2+2
  video_player: ">=0.11.0 <2.0.0"
